version: "3.3"

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
      POSTGRES_DATABASE: "dev"

  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    depends_on:
      - "postgres"

  snippets:
    build:
      context: "."
      dockerfile: "./ranna-snippets/Dockerfile"
    image: "snippets"
    environment:
      CONNECTIONSTRINGS__POSTGRESQL: "Host=postgres;Username=dev;Password=dev;Database=dev"
      CORS__ALLOWEDORIGINS: "http://localhost:5000,http://localhost:3000"
    ports:
      - "8080:8080"
